#ifndef ERROR_H
#define ERROR_H

#define FS_OPEN_FAILED 2
#define FS_READ_FAILED 3
#define FS_WRITE_FAILED 4

#define CACHE_MKDIR_FAILED 5
#define CACHE_OPEN_FAILED 6
#define CACHE_READ_FAILED 7
#define CACHE_WRITE_FAILED 8

#endif /* ERROR_H */
